<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UserRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'name' => "required|min:4|max:32",
            'email' => 'required|email',
        ];
    }

    public function messages(): array
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'name.required' => '必须输入用户名~',
            'name.min' => '最小长度为4~',
            'name.max' => '最大长度为32~'
        ];
    }
}
